//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Localization.PermissionMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesPermission {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesPermission() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Localization.PermissionMessages.MessagesPermission", typeof(MessagesPermission).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما نمیتوانید نقش Admin رو از تنها کاربر Admin سایت بگیرید.
        /// </summary>
        internal static string AtleastOneAdmin {
            get {
                return ResourceManager.GetString("AtleastOneAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش ادمین از سایت قابل حذف نیست.
        /// </summary>
        internal static string CantDeleteRoleAdmin {
            get {
                return ResourceManager.GetString("CantDeleteRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نقش ادمین قابل ادیت نیست.
        /// </summary>
        internal static string CantEditNameRoleAdmin {
            get {
                return ResourceManager.GetString("CantEditNameRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی با آیدی های {0} موجود نیست..
        /// </summary>
        internal static string PermissionIdsNotFound {
            get {
                return ResourceManager.GetString("PermissionIdsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش از قبل دارای این دسترسی نیست.
        /// </summary>
        internal static string RoleDoesntHavePermissionBefore {
            get {
                return ResourceManager.GetString("RoleDoesntHavePermissionBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این دسترسی قبلا به نقش اختصاص یافته است.
        /// </summary>
        internal static string RoleHasPermissionBefore {
            get {
                return ResourceManager.GetString("RoleHasPermissionBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشی با آیدی ارسال شده موجود نیست..
        /// </summary>
        internal static string RoleIdNotFound {
            get {
                return ResourceManager.GetString("RoleIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشی با آیدی های {0} موجود نیست..
        /// </summary>
        internal static string RoleIdsNotFound {
            get {
                return ResourceManager.GetString("RoleIdsNotFound", resourceCulture);
            }
        }
    }
}
