//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما به علت بیش از حد وارد کردن رمز عبور اشتباه تا {0} دقیقه قفل میباشد.
        /// </summary>
        internal static string AccountIsLocked {
            get {
                return ResourceManager.GetString("AccountIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد زیر رمز عبور جدید شما در سایت است. لطفا پس از ورود رمز خود را تغییر دهید: {0}.
        /// </summary>
        internal static string BodySmsMessageForgetPassword {
            get {
                return ResourceManager.GetString("BodySmsMessageForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رو به رو را جهت تایید حساب کاربری خود در قسمت مربوطه وارد کنید: {0}.
        /// </summary>
        internal static string BodySmsMessageToEnterTheCode {
            get {
                return ResourceManager.GetString("BodySmsMessageToEnterTheCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رو به رو را در قسمت مربوطه برای ورود به حساب کاربری خود وارد نمایید: {0}.
        /// </summary>
        internal static string BodySmsMessageToOTP {
            get {
                return ResourceManager.GetString("BodySmsMessageToOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده اشتباه است.
        /// </summary>
        internal static string CodeEnteredIsIncorrect {
            get {
                return ResourceManager.GetString("CodeEnteredIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده قبلا برای کاربر دیگری ثبت شده است.
        /// </summary>
        internal static string EmailIsAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailIsAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید به شماره موبایل شما ارسال شد. لطفا پس از ورود رمز عبور خود را تغییر دهید.
        /// </summary>
        internal static string NewPasswordForForgetPasswordSentToPhoneNumber {
            get {
                return ResourceManager.GetString("NewPasswordForForgetPasswordSentToPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری شما تایید نشده. لطفا ابتدا شماره موبایل خود را تایید کنید.
        /// </summary>
        internal static string PhoneNumberAndAccountIsNotConfirmed {
            get {
                return ResourceManager.GetString("PhoneNumberAndAccountIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل یافت نشد.
        /// </summary>
        internal static string PhoneNumberIsNotFound {
            get {
                return ResourceManager.GetString("PhoneNumberIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل یا رمز موقت اشتباه است.
        /// </summary>
        internal static string PhoneNumberOrOTPCodeIsWrong {
            get {
                return ResourceManager.GetString("PhoneNumberOrOTPCodeIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل یا پسورد اشتباه است.
        /// </summary>
        internal static string PhoneNumberOrPasswordIsWrong {
            get {
                return ResourceManager.GetString("PhoneNumberOrPasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان انقضای رفرش توکن به اتمام رسیده.
        /// </summary>
        internal static string RefreshTokenIsExpire {
            get {
                return ResourceManager.GetString("RefreshTokenIsExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفرش توکن ارسال شده موجود نیست.
        /// </summary>
        internal static string RefreshTokenIsNotFound {
            get {
                return ResourceManager.GetString("RefreshTokenIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید حساب کاربری به شماره موبایل شما ارسال شد.
        /// </summary>
        internal static string VerificationCodeSentToPhoneNumber {
            get {
                return ResourceManager.GetString("VerificationCodeSentToPhoneNumber", resourceCulture);
            }
        }
    }
}
