<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.10.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localization\AccountMessages\MessagesAccount.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessagesAccount.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\AccountMessages\MessagesIdentity.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessagesIdentity.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\CategoryMessages\MessagesCategory.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessagesCategory.resx</DependentUpon>
    </Compile>
    <Compile Update="Localization\PermissionMessages\MessagesPermission.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessagesPermission.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\AccountMessages\MessagesAccount.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MessagesAccount.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\AccountMessages\MessagesIdentity.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MessagesIdentity.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\CategoryMessages\MessagesCategory.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MessagesCategory.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localization\PermissionMessages\MessagesPermission.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MessagesPermission.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
